# Generated by Django 5.1.5 on 2025-01-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mi_negocio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio',
            field=models.CharField(max_length=10),
        ),
    ]
