# Generated by Django 5.1.5 on 2025-01-19 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mi_negocio', '0005_articulo_tienda_tienda_propietario_alter_articulo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mi_negocio.tienda'),
        ),
    ]
