# Generated by Django 5.1.5 on 2025-01-19 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mi_negocio', '0006_alter_articulo_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='Mi_negocio.tienda'),
        ),
    ]
