# Generated by Django 5.1.5 on 2025-01-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mi_negocio', '0007_alter_articulo_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(upload_to='articulos/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
