# Generated by Django 5.1.5 on 2025-01-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mi_negocio', '0008_alter_articulo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(upload_to='articulos/<bound method Field.__str__ of <django.db.models.fields.related.ForeignKey>>'),
        ),
    ]
