# Generated by Django 5.1.5 on 2025-01-30 20:30

import Mi_negocio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mi_negocio', '0011_alter_articulo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(upload_to=Mi_negocio.models.upload_to_articulos),
        ),
    ]
